StudentManagementPortal/Areas/Admin/Controllers/EnrollmentController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StudentManagement.DataAccessLayer.Data;
using StudentManagement.Model;

namespace StudentManagementPortal.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class EnrollmentController : Controller
    {
        private readonly ApplicationDbContext _dbContext;
        public EnrollmentController(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }
        // GET: EnrollmentController
        public IActionResult Index()
        {
            IEnumerable<Enrollment> objList = _dbContext.Enrollments
                .Include(e => e.Course)
                .Include(e => e.Student);
            return View(objList);
        }

        // GET: EnrollmentController/GetDetails/5
        public IActionResult GetDetails(long? id)
        {
            IEnumerable<Enrollment> objList = _dbContext.Enrollments
                .Include(e => e.Course)
                .Include(e => e.Student)
                .Where(m => m.Id == id);
            return View(objList);
        }

        // GET: EnrollmentController/Create
        public IActionResult Create()
        {
            ViewData["CourseID"] = new SelectList(_dbContext.Courses, "Id", "courseName");
            ViewData["StudentID"] = new SelectList(_dbContext.Students, "Id", "Name");
            return View();
        }

        // POST: EnrollmentController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,CourseID,StudentID")] Enrollment enrollment)
        {
            try
            {
                foreach (var item in _dbContext.Enrollments)
                {
                    if (item.CourseID == enrollment.CourseID && item.StudentID == enrollment.StudentID)
                    {
                        ModelState.AddModelError("CourseID", "The student is already enrolled in this course");
                        return View(enrollment);
                    }
                }
                _dbContext.Add(enrollment);
                await _dbContext.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            catch
            {
                return View();
            }
        }

        // GET: EnrollmentController/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null || _dbContext.Enrollments == null)
            {
                return NotFound();
            }

            //var enrollment = await _dbContext.Enrollments.FirstOrDefaultAsync(x=>x.Id==id);
            var enrollment = await _dbContext.Enrollments.FindAsync(id);
            if (enrollment == null)
            {
                return NotFound();
            }

            ViewData["CourseID"] = new SelectList(_dbContext.Courses, "Id", "courseName");
            ViewData["StudentID"] = new SelectList(_dbContext.Students, "Id", "Name");
            return View(enrollment);
        }

        // POST: EnrollmentController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,CourseID,StudentID")] Enrollment enrollment)
        {
            if (id != enrollment.Id)
            {
                return NotFound();
            }
            try
            {
                _dbContext.Update(enrollment);
                await _dbContext.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!EnrollmentExists(enrollment.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction("Index");
        }

        // GET: Enrollments/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null || _dbContext.Enrollments == null)
            {
                return NotFound();
            }

            var enrollment = await _dbContext.Enrollments
                .Include(e => e.Course)
                .Include(e => e.Student)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (enrollment == null)
            {
                return NotFound();
            }

            return View(enrollment);
        }

        // POST: Enrollments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            if (_dbContext.Enrollments == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Enrollments'  is null.");
            }
            var enrollment = await _dbContext.Enrollments.FindAsync(id);
            if (enrollment != null)
            {
                _dbContext.Enrollments.Remove(enrollment);
            }

            await _dbContext.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool EnrollmentExists(long id)
        {
            return (_dbContext.Enrollments?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

StudentManagementPortal/Areas/Admin/Views/Enrollment/Create.cshtml
@model Enrollment
@{
    ViewData["Title"] = "Create";
}

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Enroll Student </h2>
            <hr />
        </div>

        <div asp-validation-summary="All"></div>

    <table class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th class="col-6"><label asp-for="StudentID"class="col-6">StudentName</label></th>
                <th class="col-6"><label asp-for="CourseID" class="col-6">CourseName</label></th>
            </tr>
        </thead>
        
        <tbody>
            <tr>
            <td class="col-6">
                <select asp-for="StudentID" class="form-control col-6" asp-items="ViewBag.StudentID"></select>
                <span asp-validation-for="StudentID" class="text-danger"></span>
            </td>
            <td class="col-6">
                <select asp-for="CourseID" class="form-control col-6" asp-items="ViewBag.CourseID"></select>
                <span asp-validation-for="CourseID" class="text-danger"></span>
            </td>    
            </tr>

            <tr> 
            <td class="col-6">
                <button type="submit" class="btn btn-primary">Submit</button>
                <a asp-controller="Enrollment" asp-action="Index" class="btn btn-secondary">Back to Homepage</a> 
            </td>    
            </tr> 
        </tbody>      
    </table>
</div>
</form>

@section Scripts{
@{
    <partial name="_ValidationScriptsPartial" />
 }
}

StudentManagementPortal/Areas/Admin/Views/Enrollment/Delete.cshtml
@model Enrollment
@{
    ViewData["Title"] = "Delete";
}

<div>
    <h4>Enrollment</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Course)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Course.courseName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Student)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Student.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
          <button type="submit" class="btn btn-primary">Delete</button>
        <a asp-controller="Enrollment" asp-action="Index" class="btn btn-secondary">Back to Homepage</a>
    </form>
</div>



    

           

StudentManagementPortal/Areas/Admin/Views/Enrollment/Edit.cshtml
@model Enrollment
@{
    ViewData["Title"] = "Edit";
}

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Edit Enrolled Student </h2>
            <hr />
        </div>

        <div asp-validation-summary="All"></div>
        
   <table class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th class="col-6"><label asp-for="StudentID"class="col-6">StudentName</label></th>
                <th class="col-6"><label asp-for="CourseID" class="col-6">CourseName</label></th>
            </tr>
        </thead>
        
        <tbody>
            <tr>
            <td class="col-6">
            <select asp-for="StudentID" class="form-control col-6" asp-items="ViewBag.StudentID"></select>
            <span asp-validation-for="StudentID" class="text-danger"></span>
            </td>
            <td class="col-6">
            <select asp-for="CourseID" class="form-control col-6" asp-items="ViewBag.CourseID"></select>
            <span asp-validation-for="CourseID" class="text-danger"></span>
            </td>    
            </tr>

            <tr> 
            <td class="col-6">
            <button type="submit" class="btn btn-primary">Update</button>
            <a asp-controller="Enrollment" asp-action="Index" class="btn btn-secondary">Back to Homepage</a> 
            </td>    
            </tr>
        
        </tbody>      
    </table>
</div>
</form>

@section Scripts{
    @{
    <partial name="_ValidationScriptsPartial" />
    }
}

StudentManagementPortal/Areas/Admin/Views/Enrollment/GetDetails.cshtml
@model IEnumerable<Enrollment>
@{
    ViewData["Title"] = "GetDetails";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Enroll Student in Course</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Enrollment" asp-action="Create" class="btn btn-primary">
            <i class="bi bi-plus-circle"></i> &nbsp; Enroll New Student</a>
        </div>
    </div>

    <table class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th class="col-1">Student Id</th>
                <th class="col-3">Student Name</th>
                <th class="col-1">Course Id</th>
                <th class="col-3">Course Name</th>
            </tr>
        </thead>
    
        <tbody>
            @foreach(var item in Model)
            {
                <tr>
                    <td>
                       @item.StudentID
                    </td>
                    <td>
                       @Html.DisplayFor(modelItem => item.Student.Name)
                    </td>
                    <td>
                        @item.CourseID
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Course.courseName)
                    </td>
                    <td>
                       <div class="btn-group" role="group">
                           <a asp-controller="Enrollment" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary mx-2">
                           <i class="bi bi-pencil-square"></i>&nbsp;Edit</a>
                       </div>
                    </td>
                    <td>
                       <div class="btn-group" role="group">
                           <a asp-controller="Enrollment" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger mx-2">
                           <i class="bi bi-x-square"></i>&nbsp;Delete</a>
                       </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>                 

StudentManagementPortal/Areas/Admin/Views/Enrollment/Index.cshtml
@model IEnumerable<Enrollment>
@{
    ViewData["Title"] = "Index";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Enroll Student in Course</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Enrollment" asp-action="Create" class="btn btn-primary">
            <i class="bi bi-plus-circle"></i> &nbsp; Enroll Student</a>
        </div>
    </div>

    <table class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th class="col-1">Student Id</th>
                <th class="col-3">Student Name</th>
                <th class="col-1">Course Id</th>
                <th class="col-3">Course Name</th>
            </tr>
        </thead>
    
        <tbody>
            @foreach(var item in Model)
            {
                <tr>
                    <td>
                       @item.StudentID
                    </td>
                    <td>
                       @Html.DisplayFor(modelItem => item.Student.Name)
                    </td>
                    <td>
                        @item.CourseID
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Course.courseName)
                    </td>
                    <td>
                       <div class="btn-group" role="group">
                           <a asp-controller="Enrollment" asp-action="GetDetails" asp-route-id="@item.Id" class="btn btn-primary mx-2">
                           Details</a>
                       </div>
                    </td>
                    <td>
                       <div class="btn-group" role="group">
                           <a asp-controller="Enrollment" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary mx-2">
                           <i class="bi bi-pencil-square"></i>&nbsp;Edit</a>
                       </div>
                    </td>
                    <td>
                       <div class="btn-group" role="group">
                           <a asp-controller="Enrollment" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger mx-2">
                           <i class="bi bi-x-square"></i>&nbsp;Delete</a>
                       </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>                 