StudentManagement/Controllers/CourseController.cs
using Microsoft.AspNetCore.Mvc;
using StudentManagement.Data;
using StudentManagement.Model;

namespace WebApplicationMVCTest.Controllers
{
    public class CourseController : Controller
    {
        private readonly ApplicationDbContext _dbContext;
         public CourseController(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public IActionResult Index()
        {
            IEnumerable<Course> objCourseList = _dbContext.Courses;
            return View(objCourseList);
        }

        //GET
        public IActionResult AddCourse()
        {
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddCourse(Course _course)
        {
            if (ModelState.IsValid)
            {
                _dbContext.Courses.Add(_course);
                _dbContext.SaveChanges();
                TempData["success"] = "Course Added successfully!!";
                return RedirectToAction("Index");
            }
            return View(_course);
        }

        //GET
        public IActionResult EditCourse(long? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var courseFromDb = _dbContext.Courses.Find(id);

            if (courseFromDb == null)
            {
                return NotFound();
            }
            return View(courseFromDb);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditCourse(Course _course)
        {
            //if (obj.Name == obj.DisplayOrder.ToString())
            //{
            //    ModelState.AddModelError("Name", "The DisplayOrder cannot exactly match the name");
            //}
            if (ModelState.IsValid)
            {
                _dbContext.Courses.Update(_course);
                _dbContext.SaveChanges();
                TempData["success"] = "Course Updated successfully!!";
                return RedirectToAction("Index");
            }
            return View(_course);
        }


        //GET
        public IActionResult DeleteCourse(long? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var courseFromDb = _dbContext.Courses.Find(id);

            if (courseFromDb == null)
            {
                return NotFound();
            }
            return View(courseFromDb);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(long? id)
        {
            var obj = _dbContext.Courses.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            _dbContext.Courses.Remove(obj);
            _dbContext.SaveChanges();
            TempData["success"] = "Course Deleted successfully!!";
            return RedirectToAction("Index");
        }


    }
}

StudentManagement/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using StudentManagement.Model;
using System.Diagnostics;

namespace WebApplicationMVCTest.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

StudentManagement/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using StudentManagement.Data;
using StudentManagement.Model;

namespace WebApplicationMVCTest.Controllers
{
    public class StudentController : Controller
    {
        private readonly ApplicationDbContext _dbContext;

        public StudentController(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }
        public IActionResult Index()
        {
            IEnumerable<Student> objStudentList = _dbContext.Students;
            return View(objStudentList);
        }

        public IActionResult GetDetails()
        {
            IEnumerable<Student> objStudentList = _dbContext.Students;
            return View(objStudentList);
        }

        //GET
        public IActionResult AddStudent()
        {
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddStudent(Student _student)
        {
            //if (obj.Name == obj.DisplayOrder.ToString())
            //{
            //    ModelState.AddModelError("Name", "The DisplayOrder cannot exactly match the name");
            //}
            if (ModelState.IsValid)
            {
                _dbContext.Students.Add(_student);
                _dbContext.SaveChanges();
                TempData["success"] = "Student Added successfully!!";
                return RedirectToAction("Index");
            }
            return View(_student);
        }


        //GET
        public IActionResult EditStudent(long? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var studentFromDb = _dbContext.Students.Find(id);

            if (studentFromDb == null)
            {
                return NotFound();
            }
            return View(studentFromDb);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditStudent(Student _student)
        {
            //if (obj.Name == obj.DisplayOrder.ToString())
            //{
            //    ModelState.AddModelError("Name", "The DisplayOrder cannot exactly match the name");
            //}
            if (ModelState.IsValid)
            {
                _dbContext.Students.Update(_student);
                _dbContext.SaveChanges();
                TempData["success"] = "Student Updated successfully!!";
                return RedirectToAction("Index");
            }
            return View(_student);
        }


        //GET
        public IActionResult DeleteStudent(long? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var studentFromDb = _dbContext.Students.Find(id);

            if (studentFromDb == null)
            {
                return NotFound();
            }
            return View(studentFromDb);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(long? id)
        {
            var obj = _dbContext.Students.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            _dbContext.Students.Remove(obj);
            _dbContext.SaveChanges();
            TempData["success"] = "Student Deleted successfully!!";
            return RedirectToAction("Index");
        }
    }
}

StudentManagement/Views/Course/AddCourse.cshtml
@model Course
@{
    ViewData["Title"] = "AddCourse";
}

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Add New Course</h2>
            <hr />
        </div>

        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <label asp-for="courseName"></label>
            <input asp-for="courseName" class="form-control"/>
            <span asp-validation-for="courseName" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="courseDuration"></label>
            <input asp-for="courseDuration" class="form-control"/>
            <span asp-validation-for="courseDuration" class="text-danger"></span>
        </div>
      
        <button type="submit" class="btn btn-primary">Submit</button>
        <a asp-controller="Course" asp-action="Index" class="btn btn-secondary">Back to Homepage</a>
    </div>
</form>

@section Scripts{
    @{
    <partial name="_ValidationScriptsPartial" />
    }
}

StudentManagement/Views/Course/DeleteCourse.cshtml
@model Course
@{
    ViewData["Title"] = "DeleteCourse";
}

<form method="post" asp-action="DeletePost">
    <input asp-for="Id" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Delete Course Details</h2>
            <hr />
        </div>
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <label asp-for="courseName"></label>
            <input asp-for="courseName" disabled class="form-control"/>
            <span asp-validation-for="courseName" class="text-danger"></span>
        </div>s
        <div class="mb-3">
            <label asp-for="courseDuration"></label>
            <input asp-for="courseDuration" disabled class="form-control"/>
            <span asp-validation-for="courseDuration" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary">Delete</button>
        <a asp-controller="Student" asp-action="Index" class="btn btn-secondary">Back to Homepage</a>
    </div>
</form>

@section Scripts{
    @{
    <partial name="_ValidationScriptsPartial" />
    }
}

StudentManagement/Views/Course/EditCourse.cshtml
@model Course
@{
    ViewData["Title"] = "EditCourse";
}

<form method="post" asp-action="EditCourse">
     <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Edit Course Details</h2>
            <hr />
        </div>
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <label asp-for="courseName"></label>
            <input asp-for="courseName" class="form-control"/>
            <span asp-validation-for="courseName" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="courseDuration"></label>
            <input asp-for="courseDuration" class="form-control"/>
            <span asp-validation-for="courseDuration" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary">Update</button>
        <a asp-controller="Course" asp-action="Index" class="btn btn-secondary">Back to Homepage</a>
    </div>
</form>

@section Scripts{
    @{
    <partial name="_ValidationScriptsPartial" />
    }
}

StudentManagement/Views/Course/Index.cshtml
@model IEnumerable<Course>
@{
    ViewData["Title"] = "Index";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Manage Course</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Course" asp-action="AddCourse" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i> &nbsp; Add New Course</a>
        </div>
    </div>

    <table class="table table-bordered table-striped" style="width:100%">

        <thead>
            <tr>
                <th class="col-2">ID</th>
                <th class="col-4">Course Name</th>
                <th class="col-4">Course Duration</th>
            </tr>
        </thead>
    
        <tbody>
            @foreach(var course in Model)
            {
                <tr>
                    <td>
                        @course.Id
                    </td>
                    <td>
                        @course.courseName
                    </td>
                     <td>
                        @course.courseDuration
                    </td>
                    <td>
                       <div class="btn-group" role="group">
                           <a asp-controller="Course" asp-action="EditCourse" asp-route-id="@course.Id" class="btn btn-primary mx-2">
                           <i class="bi bi-pencil-square"></i>&nbsp;Edit</a>
                       </div>
                    </td>
                    <td>
                       <div class="btn-group" role="group">
                           <a asp-controller="Course" asp-action="DeleteCourse" asp-route-id="@course.Id" class="btn btn-danger mx-2">
                           <i class="bi bi-x-square"></i>&nbsp;Delete</a>
                       </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

StudentManagement/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

StudentManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Student Management Portal</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplicationMVCTest.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Student Management Portal</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Manage Student</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="Index">Manage Course</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Student Management  Portal - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

StudentManagement/Views/Student/AddStudent.cshtml
@model Student
@{
    ViewData["Title"] = "AddStudent";
}

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Add New Student</h2>
            <hr />
        </div>

        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control"/>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Age"></label>
            <input asp-for="Age" class="form-control"/>
            <span asp-validation-for="Age" class="text-danger"></span>
        </div>
         <div class="mb-3">
            <label asp-for="Gender"></label>
            <input type="radio" asp-for="Gender" class="form-control" value="Male" />Male
            <input type="radio" asp-for="Gender" class="form-control" value="Female" />Female
            <input type="radio" asp-for="Gender" class="form-control" value="Others" />Others
            <span asp-validation-for="Gender" class="text-danger"></span>
         </div>
         <div class="mb-3">
            <label asp-for="Email"></label>
            <input asp-for="Email" class="form-control"/>
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
         <div class="mb-3">
            <label asp-for="PhoneNo"></label>
            <input asp-for="PhoneNo" class="form-control"/>
            <span asp-validation-for="PhoneNo" class="text-danger"></span>
        </div>
         <div class="mb-3">
            <label asp-for="Address"></label>
            <input asp-for="Address" class="form-control"/>
            <span asp-validation-for="Address" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
        <a asp-controller="Student" asp-action="Index" class="btn btn-secondary">Back to Homepage</a>
    </div>
</form>

@section Scripts{
    @{
    <partial name="_ValidationScriptsPartial" />
    }
}

StudentManagement/Views/Student/DeleteStudent.cshtml
@model Student
@{
    ViewData["Title"] = "DeleteStudent";
}

<form method="post" asp-action="DeletePost">
    <input asp-for="Id" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Delete Student Details</h2>
            <hr />
        </div>
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" disabled class="form-control"/>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Age"></label>
            <input asp-for="Age" disabled class="form-control"/>
            <span asp-validation-for="Age" class="text-danger"></span>
        </div>
         <div class="mb-3">
            <label asp-for="Gender"></label>
            <input asp-for="Gender" disabled class="form-control"/>
            <span asp-validation-for="Gender" class="text-danger"></span>
        </div>
         <div class="mb-3">
            <label asp-for="Email"></label>
            <input asp-for="Email" disabled class="form-control"/>
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
         <div class="mb-3">
            <label asp-for="PhoneNo"></label>
            <input asp-for="PhoneNo" disabled class="form-control"/>
            <span asp-validation-for="PhoneNo" class="text-danger"></span>
        </div>
         <div class="mb-3">
            <label asp-for="Address"></label>
            <input asp-for="Address" disabled class="form-control"/>
            <span asp-validation-for="Address" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary">Delete</button>
        <a asp-controller="Student" asp-action="Index" class="btn btn-secondary">Back to Homepage</a>
    </div>
</form>

@section Scripts{
    @{
    <partial name="_ValidationScriptsPartial" />
    }
}

StudentManagement/Views/Student/EditStudent.cshtml
@model Student
@{
    ViewData["Title"] = "EditStudent";
}

<form method="post" asp-action="EditStudent">
     <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Edit Student Details</h2>
            <hr />
        </div>
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control"/>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Age"></label>
            <input asp-for="Age" class="form-control"/>
            <span asp-validation-for="Age" class="text-danger"></span>
        </div>
         <div class="mb-3">
            <label asp-for="Gender"></label>
            <input asp-for="Gender" class="form-control"/>
            <span asp-validation-for="Gender" class="text-danger"></span>
        </div>
         <div class="mb-3">
            <label asp-for="Email"></label>
            <input asp-for="Email" class="form-control"/>
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
         <div class="mb-3">
            <label asp-for="PhoneNo"></label>
            <input asp-for="PhoneNo" class="form-control"/>
            <span asp-validation-for="PhoneNo" class="text-danger"></span>
        </div>
         <div class="mb-3">
            <label asp-for="Address"></label>
            <input asp-for="Address" class="form-control"/>
            <span asp-validation-for="Address" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary">Update</button>
        <a asp-controller="Student" asp-action="Index" class="btn btn-secondary">Back to Homepage</a>
    </div>
</form>

@section Scripts{
    @{
    <partial name="_ValidationScriptsPartial" />
    }
}

StudentManagement/Views/Student/GetDetails.cshtml
@model IEnumerable<Student>
@{
    ViewData["Title"] = "GetDetails";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Student Details</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Student" asp-action="AddStudent" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i> &nbsp; Add New Student</a>
        </div>

    </div>


    <table class="table table-bordered table-striped" style="width:100%">

        <thead>
            <tr>
                <th class="col-1">ID</th>
                <th class="col-2">Student Name</th>
                <th class="col-1">Age</th>
                <th class="col-1">Gender</th>
                <th class="col-3">Email</th>
                <th class="col-1">Phone No</th>
                <th class="col-3">Address</th>

            </tr>
        </thead>
    
        <tbody>
            @foreach(var student in Model)
            {
                <tr>
                    <td>
                        @student.Id
                    </td>
                    <td>
                        @student.Name
                    </td>
                    <td>
                        @student.Age
                    </td>
                    <td>
                        @student.Gender
                    </td>
                    <td>
                        @student.Email
                    </td>
                    <td>
                        @student.PhoneNo
                    </td>
                    <td>
                        @student.Address
                    </td>
                    <td>
                       <div class="btn-group" role="group">
                           <a asp-controller="Student" asp-action="EditStudent" asp-route-id="@student.Id" class="btn btn-primary mx-2">
                           <i class="bi bi-pencil-square"></i>&nbsp;Edit</a>
                       </div>
                    </td>
                    <td>
                       <div class="btn-group" role="group">
                           <a asp-controller="Student" asp-action="DeleteStudent" asp-route-id="@student.Id" class="btn btn-danger mx-2">
                           <i class="bi bi-x-square"></i>&nbsp;Delete</a>
                       </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

StudentManagement/Views/Student/Index.cshtml
@model IEnumerable<Student>
@{
    ViewData["Title"] = "Index";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Manage Student</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Student" asp-action="AddStudent" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i> &nbsp; Add New Student</a>
        </div>

    </div>


    <table class="table table-bordered table-striped" style="width:100%">

        <thead>
            <tr>
                <th class="col-3">ID</th>
                <th class="col-3">Student Name</th>
             @*   <th class="col-1">Age</th>
                <th class="col-1">Gender</th>
*@                <th class="col-3">Email</th>
  @*              <th class="col-2">Phone No</th>
                <th class="col-3">Address</th>
*@
            </tr>
        </thead>
    
        <tbody>
            @foreach(var student in Model)
            {
                <tr>
                    <td>
                        @student.Id
                    </td>
                    <td>
                        @student.Name
                    </td>
                    @*<td>
                        @student.Age
                    </td>
                    <td>
                        @student.Gender
                    </td>
                    *@
                    <td>
                        @student.Email
                    </td>
                    @*<td>
                        @student.PhoneNo
                    </td>
                    <td>
                        @student.Address
                    </td>*@
                    <td>
                       <div class="btn-group" role="group">
                           <a asp-controller="Student" asp-action="GetDetails" asp-route-id="@student.Id" class="btn btn-primary mx-2">
                           <i class="bi bi-pencil-square"></i>&nbsp;Details</a>
                       </div>
                    </td>
                    <td>
                       <div class="btn-group" role="group">
                           <a asp-controller="Student" asp-action="EditStudent" asp-route-id="@student.Id" class="btn btn-primary mx-2">
                           <i class="bi bi-pencil-square"></i>&nbsp;Edit</a>
                       </div>
                    </td>
                    <td>
                       <div class="btn-group" role="group">
                           <a asp-controller="Student" asp-action="DeleteStudent" asp-route-id="@student.Id" class="btn btn-danger mx-2">
                           <i class="bi bi-x-square"></i>&nbsp;Delete</a>
                       </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>